package com.ships.controllers;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.ships.model.OrderInfo;
import com.ships.model.Ship;
import com.ships.model.ShippingCompany;
import com.ships.services.OrderService;
import com.ships.services.ShipsService;
import com.ships.services.CompanyService;

@Controller // This means that this class is a Controller
public class OrderController 
{
	@Autowired // Bean called orderService is auto-generated by Spring, which will use it to handle the data
	private OrderService orderService;
	
	@Autowired // Bean called shipsService is auto-generated by Spring, which will use it to handle the data
	private ShipsService shipsService;
	
	@Autowired // Bean called CompanyService is auto-generated by Spring, which will use it to handle the data
	private CompanyService CompanyService;

	// Method to display all orders in the 'order' table
	@RequestMapping(value = "/showOrders", method = RequestMethod.GET)
	public String getOrders(Model model)
	{
		ArrayList<OrderInfo> orderList = orderService.listAll();
		
		model.addAttribute("orderList", orderList);
		
		return "showOrders";
	}
	
	// Create order method (GET)
	@RequestMapping(value = "/addOrder", method = RequestMethod.GET)
	public String getOrder(@ModelAttribute("orderAdd") OrderInfo o, HttpServletRequest h, Model model) 
	{
		ArrayList<Ship> ships = shipsService.listAll();
		
		Map<Long,String> orderShipList = new HashMap<Long,String>();
		
		// For every ship
		for (Ship s : ships)
		{	
			if (s.getShippingCompany() == null)
			{
			orderShipList.put((long) s.getSid(), s.getName() + ", Cost = " + s.getCost());
			}
		}
		
		model.addAttribute("shippingList", orderShipList);
		
		// Create an array list of all our shipping companies from our Shipping Company Service
		ArrayList<ShippingCompany> companies = CompanyService.listAll();
		
		Map<Long,String> companyList = new HashMap<Long,String>();
		
		for (ShippingCompany sc : companies) 
		{	
			companyList.put((long) sc.getScid(), sc.getName() + ", Balance = " + sc.getBalance());
		}
		
		model.addAttribute("orderCompanyList", companyList);
				
	
		return "addOrder";
	}
	
	// Create order method (POST)
	@RequestMapping(value = "/addOrder", method = RequestMethod.POST)
	public String addShip(@Valid @ModelAttribute("orderAdd") OrderInfo o, BindingResult result, HttpServletRequest h, Model model) 
	{

		// If there are errors, prompt the user
		if (o.getShip()==null || o.getShippingCompany()==null)
		{
			return "noShipOrCompany";
		}
		else if (o.getShip().getCost().compareTo(o.getShippingCompany().getBalance()) == (0|1))
		{
			return "noMoney";
		}
		
		// If there are no errors, continue
		else 
		{
			System.out.println("In Else statement");
			o.getShippingCompany().setBalance(o.getShippingCompany().getBalance().subtract(o.getShip().getCost()));

			orderService.save(o);
			shipsService.addShip(o.getShip());
			CompanyService.addShipCompany(o.getShippingCompany());
			
			ArrayList<OrderInfo> orders = orderService.listAll();
	
			model.addAttribute("orders", orders);
		
			// Once the order has been placed, redirect the user and refresh the page to show them the changes they just made
			return "redirect:showOrders";
		}
	}
}