package com.ships.controllers;

import java.util.ArrayList;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.ships.model.Ship;
import com.ships.services.ShipsService;

@Controller // This means that this class is a Controller
public class ShipController {
	@Autowired // Bean called shipsService is auto-generated by Spring, which will use it to handle the data
	private ShipsService shipsService;

	// Method to display all ships in the 'ship' table
	@RequestMapping(value = "/showShips", method = RequestMethod.GET)
	public String getShips(Model s) {
		ArrayList<Ship> shipList = shipsService.listAll();

		s.addAttribute("shipList", shipList);

		return "showShips";
	}

	// GET method to add a new ship to the 'ship' table
	@RequestMapping(value = "/addShip", method = RequestMethod.GET)
	public String getShips(@ModelAttribute("shipAdd") Ship m, HttpServletRequest h) {
		return "addShip";
	}

	// POST method to add a new ship to the 'ship' table
	@RequestMapping(value = "/addShip", method = RequestMethod.POST)
	public String addShip(@Valid @ModelAttribute("shipAdd") Ship m, BindingResult result, HttpServletRequest h,
			Model s) {
		// If there are errors, prompt the user
		if (result.hasErrors()) {
			return "addShip";
		}

		// If there are no errors, continue
		else {
			shipsService.addShip(m);

			ArrayList<Ship> shipList = shipsService.listAll();

			s.addAttribute("shipList", shipList);

			// Once the Ship has been added, redirect the user and refresh the page to show them the changes they just made
			return "redirect:showShips";
		}
	}
}