package com.ships.controllers;

import java.util.ArrayList;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.ships.model.Ship;
import com.ships.services.ShipsService;

@Controller
public class ShipController 
{
	@Autowired // This means to get the bean called shipService, Which is auto-generated by Spring, we will use it to handle the data
	private ShipsService shipsService;
	
	
	// Setup our method to display all ships in the 'ship' table
	@RequestMapping(value = "/showShips", method = RequestMethod.GET)	
	public String getShips(Model s)
	{
		ArrayList<Ship> shipList = shipsService.listAll();
		
		s.addAttribute("shipList", shipList);
		
		return "showShips";
	}
	
	// Setup our GET method to add a new ship to the 'ship' table
	@RequestMapping(value = "/addShip", method = RequestMethod.GET)	
	public String getShips(@ModelAttribute("shipAdd") Ship m, HttpServletRequest h)
	{
		return "addShip";
	}
	
	// Setup our POST method to add a new ship to the 'ship' table
	@RequestMapping(value = "/addShip", method = RequestMethod.POST)	
	public String addShip(@Valid @ModelAttribute("shipAdd") Ship m, BindingResult result, HttpServletRequest h, Model s)
	{
			// First, check for errors
		if (result.hasErrors())
		{
			return "addShip";
		}		
		else
		{
			shipsService.addShip(m);
			
			ArrayList<Ship> shipList = shipsService.listAll();
			
			s.addAttribute("shipList", shipList);
			
			return "showShips";
		}
	}
}