package com.ships.services;

import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.ships.model.ShippingCompany;
import com.ships.repositories.CompanyInterface;

@Service // Define the following class as a service (https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/stereotype/Service.html)
public class CompanyService
{
	@Autowired // Bean called CompanyInterface is auto-generated by Spring, which will use it to handle the data
	private CompanyInterface CompanyInterface;
	
	public ArrayList<ShippingCompany> listAll()
	{
		// Find all elements in the 'Ship' table and put them in an ArrayList called 'ShippingCompany'
		return (ArrayList<ShippingCompany>) CompanyInterface.findAll();
	}
	
	public ShippingCompany addShipCompany(ShippingCompany company) {
		return CompanyInterface.save(company);
	}
}